WebMVC/Controllers/QueueMembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.Entities;
using DAL.Implementation;
using BL.Abstraction;
using BL.DTO.Models;
using System.Security.Claims;

namespace WebMVC.Controllers
{
    public class QueueMembersController : Controller
    {
        private readonly IQueueMemberService _service;
        private readonly IQueueService _queueService;
        private readonly IConsultationService _consultationService;

        public QueueMembersController(IQueueMemberService service, IQueueService queueService, IConsultationService consultationService)
        {
            _queueService = queueService;
            _service = service;
            _consultationService = consultationService;
        }

        // GET: QueueMembers
        public async Task<IActionResult> Index(int? consultationId)
        {
            var consultations = await _consultationService.GetAllAsync();

            var query = consultations.Select(c => new {
                Id = c.Id,
                DisplayText = String.Format("{0} {1} {2} {3}", c.Lecturer.FirstName, c.Lecturer.SecondName, c.Subject.Name, c.Date)
            });

            ViewData["ConsultationId"] = new SelectList(query, "Id", "DisplayText");

            if (consultationId is null)
            {
                return View(await _service.GetAllAsync());
            }

            var members = await _service.GetAllAsync();
            return View(members.Where(m => m.Queue.ConsultationId == consultationId));
        }

        // GET: QueueMembers/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id < 0)
            {
                return NotFound();
            }

            var queueMember = await _service.GetByIdAsync(id);
            if (queueMember == null)
            {
                return NotFound();
            }

            return View(queueMember);
        }

        // GET: QueueMembers/Create
        public async Task<IActionResult> Create()
        {
            var queues = await _queueService.GetAllAsync();

            var query = queues.Select(q => new
            {
                Id = q.Id,
                DisplayText = String.Format("{0} {1} {2} {3}", q.Consultation.Lecturer.SecondName, 
                q.Consultation.Subject.Name, q.Consultation.Date, q.IssueCategory.ToString())
            });

            ViewData["QueueId"] = new SelectList(query, "Id", "DisplayText");
            return View();
        }

        // POST: QueueMembers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Priority,TimeInterval,IsAbsent,QueueId,StudentId,Id")] QueueMemberDTO queueMember)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            queueMember.StudentId = userId;

            if (ModelState.IsValid)
            {
                await _service.AddAsync(queueMember);
                return RedirectToAction(nameof(Index));
            }
            var queues = await _queueService.GetAllAsync();
            ViewData["QueueId"] = new SelectList(queues, "Id", "Id", queueMember.QueueId);
            return View(queueMember);
        }

        // GET: QueueMembers/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id < 0)
            {
                return NotFound();
            }

            var queueMember = await _service.GetByIdAsync(id);
            if (queueMember == null)
            {
                return NotFound();
            }
            var queues = await _queueService.GetAllAsync();

            var query = queues.Select(q => new
            {
                Id = q.Id,
                DisplayText = String.Format("{0} {1} {2} {3}", q.Consultation.Lecturer.SecondName,
                q.Consultation.Subject.Name, q.Consultation.Date, q.IssueCategory.ToString())
            });
            ViewData["QueueId"] = new SelectList(query, "Id", "DisplayText", queueMember.QueueId);
            return View(queueMember);
        }

        // POST: QueueMembers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Priority,TimeInterval,IsAbsent,QueueId,StudentId,Id")] QueueMemberDTO queueMember)
        {
            if (id != queueMember.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _service.UpdateAsync(queueMember);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_service.QueueMemberExists(queueMember.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            var queues = await _queueService.GetAllAsync();

            var query = queues.Select(q => new
            {
                Id = q.Id,
                DisplayText = String.Format("{0} {1} {2} {3}", q.Consultation.Lecturer.SecondName,
                q.Consultation.Subject.Name, q.Consultation.Date, q.IssueCategory.ToString())
            });
            ViewData["QueueId"] = new SelectList(query, "Id", "DisplayText", queueMember.QueueId);

            return View(queueMember);
        }

        // GET: QueueMembers/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id < 0)
            {
                return NotFound();
            }

            var queueMember = await _service.GetByIdAsync(id);
            if (queueMember == null)
            {
                return NotFound();
            }

            return View(queueMember);
        }

        // POST: QueueMembers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _service.DeleteByIdAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

WebMVC/Controllers/QueuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.Entities;
using DAL.Implementation;
using BL.Abstraction;
using BL.DTO.Models;
using BL.DTO;

namespace WebMVC.Controllers
{
    public class QueuesController : Controller
    {
        private readonly IQueueService _service;
        private readonly IConsultationService _consultationService;

        public QueuesController(IQueueService service, 
                                ApplicationContext context, 
                                IConsultationService consultationService)
        {
            _service = service;
            _consultationService = consultationService;
        }

        // GET: Queues
        public async Task<IActionResult> Index()
        {

            return View(await _service.GetAllAsync());
        }

        // GET: Queues/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id < 0)
            {
                return NotFound();
            }

            var queue = await _service.GetByIdAsync(id);
            if (queue == null)
            {
                return NotFound();
            }

            return View(queue);
        }

        // GET: Queues/Create
        public async Task<IActionResult> Create()
        {
            var consultations = await _consultationService.GetAllAsync();
            
            var query = consultations.Select(c => new { Id = c.Id,
                DisplayText = String.Format("{0} {1} {2} {3}", c.Lecturer.FirstName, c.Lecturer.SecondName, c.Subject.Name, c.Date) });
            ViewData["ConsultationId"] = new SelectList(query, "Id", "DisplayText");

            var enamData = Enum.GetValues(typeof(IssueCategory))
                               .OfType<Enum>()
                               .Select(e => new { Id = Convert.ToInt32(e), Display = Enum.GetName(typeof(IssueCategory), e)});
            ViewData["IssueCategory"] = new SelectList(enamData, "Id", "Display");

            return View();
        }

        // POST: Queues/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IssueCategory,Priority,ConsultationId,Id")] QueueDTO queue)
        {
            if (ModelState.IsValid)
            {
                await _service.AddAsync(queue);
                return RedirectToAction(nameof(Index));
            }
            var consultations = await _consultationService.GetAllAsync();
            ViewData["ConsultationId"] = new SelectList(consultations, "Id", "Id", queue.ConsultationId);
            return View(queue);
        }

        // GET: Queues/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id < 0)
            {
                return NotFound();
            }

            var queue = await _service.GetByIdAsync(id);
            if (queue == null)
            {
                return NotFound();
            }

            var consultations = await _consultationService.GetAllAsync();
            ViewData["ConsultationId"] = new SelectList(consultations, "Id", "Id", queue.ConsultationId);
            return View(queue);
        }

        // POST: Queues/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IssueCategory,Priority,ConsultationId,Id")] QueueDTO queue)
        {
            if (id != queue.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _service.UpdateAsync(queue);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_service.QueueExists(queue.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            var consultations = await _consultationService.GetAllAsync();
            ViewData["ConsultationId"] = new SelectList(consultations, "Id", "Id", queue.ConsultationId);
            return View(queue);
        }

        // GET: Queues/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id < 0)
            {
                return NotFound();
            }

            var queue = await _service.GetByIdAsync(id);
            if (queue == null)
            {
                return NotFound();
            }

            return View(queue);
        }

        // POST: Queues/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _service.DeleteByIdAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

WebMVC/Controllers/SubjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.Entities;
using DAL.Implementation;
using BL.Abstraction;
using BL.DTO.Models;
using Microsoft.AspNetCore.Authorization;

namespace WebMVC.Controllers
{
    public class SubjectsController : Controller
    {
        private readonly ISubjectService _service;

        public SubjectsController(ISubjectService service)
        {
            _service = service;
        }

        // GET: Subjects
        public async Task<IActionResult> Index()
        {
            return View(await _service.GetAllAsync());
        }

        // GET: Subjects/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id < 0)
            {
                return NotFound();
            }

            var subject = await _service.GetByIdAsync(id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        // GET: Subjects/Create
        [Authorize(Roles ="lecturer")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Subjects/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Id")] SubjectDTO subject)
        {
            if (ModelState.IsValid)
            {
                await _service.AddAsync(subject);
                return RedirectToAction(nameof(Index));
            }
            return View(subject);
        }

        // GET: Subjects/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id < 0)
            {
                return NotFound();
            }

            var subject = await _service.GetByIdAsync(id);
            if (subject == null)
            {
                return NotFound();
            }
            return View(subject);
        }

        // POST: Subjects/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Id")] SubjectDTO subject)
        {
            if (id != subject.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _service.UpdateAsync(subject);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_service.SubjectExists(subject.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(subject);
        }

        // GET: Subjects/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id < 0)
            {
                return NotFound();
            }

            var subject = await _service.GetByIdAsync(id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        // POST: Subjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _service.DeleteByIdAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Subjects" asp-action="Index">Subjects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Queues" asp-action="Index">Queues</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Consultations" asp-action="Index">Consultations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="QueueMembers" asp-action="Index">QueueMembers</a>
                        </li>*@
                    </ul>
                </div>
                <ul class="flex-grow"></ul>
                @if (User is not null && !User.Identity.IsAuthenticated)
                {
                    <li style="list-style-type: none">
                        <a class="btn btn-primary mr-2" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                    </li>
                    <li style="list-style-type: none">
                        <a class="btn btn-success" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                    </li>
                }
                else
                {
                    <li class="text-dark" style="list-style-type: none">
                        <h5>@User.Identity.Name</h5>
                    </li>
                    <form method="post" asp-controller="Account" asp-action="Logout">
                        <button class="mx-2 btn btn-danger" style="align-self: flex-end" type="submit">Logout</button>
                    </form>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>