WebMVC/Controllers/ConsultationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.Entities;
using DAL.Implementation;
using BL.Abstraction;
using BL.DTO.Models;
using System.Security.Claims;

namespace WebMVC.Controllers
{
    public class ConsultationsController : Controller
    {
        private readonly IConsultationService _service;
        private readonly ISubjectService _subjectService;
        ApplicationContext _context;

        public ConsultationsController(IConsultationService service, 
                                       ApplicationContext context, 
                                       ISubjectService subjectService)
        {
            _subjectService = subjectService;
            _service = service;
            _context = context;
        }

        // GET: Consultations
        public async Task<IActionResult> Index()
        {
            return View(await _service.GetAllAsync());
        }

        // GET: Consultations/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id < 0)
            {
                return NotFound();
            }

            var consultation = await _service.GetByIdAsync(id);
            if (consultation == null)
            {
                return NotFound();
            }

            return View(consultation);
        }

        // GET: Consultations/Create
        public async Task<IActionResult> Create()
        {
            var subjects = await _subjectService.GetAllAsync();
            ViewData["Subject"] = new SelectList(subjects, "Id", "Name");
            return View();
        }

        // POST: Consultations/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Date,SubjectId,LecturerId,Id")] ConsultationDTO consultation)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            consultation.LecturerId = userId;

            if (ModelState.IsValid)
            {
                await _service.AddAsync(consultation);
                return RedirectToAction(nameof(Index));
            }

            var subjects = await _subjectService.GetAllAsync();
            ViewData["SubjectId"] = new SelectList(subjects, "Id", "Id", consultation.SubjectId);
            return View(consultation);
        }

        // GET: Consultations/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id < 0)
            {
                return NotFound();
            }

            var consultation = await _service.GetByIdAsync(id);
            if (consultation == null)
            {
                return NotFound();
            }

            var subjects = await _subjectService.GetAllAsync();
            ViewData["SubjectId"] = new SelectList(subjects, "Id", "Id", consultation.SubjectId);
            return View(consultation);
        }

        // POST: Consultations/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Date,SubjectId,LecturerId,Id")] ConsultationDTO consultation)
        {
            if (id != consultation.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _service.UpdateAsync(consultation);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_service.ConsultationExists(consultation.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            var subjects = await _subjectService.GetAllAsync();
            ViewData["SubjectId"] = new SelectList(subjects, "Id", "Id", consultation.SubjectId);
            return View(consultation);
        }

        // GET: Consultations/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id < 0)
            {
                return NotFound();
            }

            var consultation = await _service.GetByIdAsync(id);
            if (consultation == null)
            {
                return NotFound();
            }

            return View(consultation);
        }

        // POST: Consultations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _service.DeleteByIdAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

WebMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebMVC.Models;

namespace WebMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebMVC/Controllers/QueueMembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.Entities;
using DAL.Implementation;
using BL.Abstraction;
using BL.DTO.Models;
using System.Security.Claims;

namespace WebMVC.Controllers
{
    public class QueueMembersController : Controller
    {
        private readonly IQueueMemberService _service;
        private readonly IQueueService _queueService;
        private readonly IConsultationService _consultationService;

        public QueueMembersController(IQueueMemberService service, IQueueService queueService, IConsultationService consultationService)
        {
            _queueService = queueService;
            _service = service;
            _consultationService = consultationService;
        }

        // GET: QueueMembers
        public async Task<IActionResult> Index(int? consultationId)
        {
            var consultations = await _consultationService.GetAllAsync();

            var query = consultations.Select(c => new {
                Id = c.Id,
                DisplayText = String.Format("{0} {1} {2} {3}", c.Lecturer.FirstName, c.Lecturer.SecondName, c.Subject.Name, c.Date)
            });

            ViewData["ConsultationId"] = new SelectList(query, "Id", "DisplayText");

            if (consultationId is null)
            {
                return View(await _service.GetAllAsync());
            }

            var members = await _service.GetAllAsync();
            return View(members.Where(m => m.Queue.ConsultationId == consultationId));
        }

        // GET: QueueMembers/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id < 0)
            {
                return NotFound();
            }

            var queueMember = await _service.GetByIdAsync(id);
            if (queueMember == null)
            {
                return NotFound();
            }

            return View(queueMember);
        }

        // GET: QueueMembers/Create
        public async Task<IActionResult> Create()
        {
            var queues = await _queueService.GetAllAsync();

            var query = queues.Select(q => new
            {
                Id = q.Id,
                DisplayText = String.Format("{0} {1} {2} {3}", q.Consultation.Lecturer.SecondName, 
                q.Consultation.Subject.Name, q.Consultation.Date, q.IssueCategory.ToString())
            });

            ViewData["QueueId"] = new SelectList(query, "Id", "DisplayText");
            return View();
        }

        // POST: QueueMembers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Priority,TimeInterval,IsAbsent,QueueId,StudentId,Id")] QueueMemberDTO queueMember)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            queueMember.StudentId = userId;

            if (ModelState.IsValid)
            {
                await _service.AddAsync(queueMember);
                return RedirectToAction(nameof(Index));
            }
            var queues = await _queueService.GetAllAsync();
            ViewData["QueueId"] = new SelectList(queues, "Id", "Id", queueMember.QueueId);
            return View(queueMember);
        }

        // GET: QueueMembers/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id < 0)
            {
                return NotFound();
            }

            var queueMember = await _service.GetByIdAsync(id);
            if (queueMember == null)
            {
                return NotFound();
            }
            var queues = await _queueService.GetAllAsync();

            var query = queues.Select(q => new
            {
                Id = q.Id,
                DisplayText = String.Format("{0} {1} {2} {3}", q.Consultation.Lecturer.SecondName,
                q.Consultation.Subject.Name, q.Consultation.Date, q.IssueCategory.ToString())
            });
            ViewData["QueueId"] = new SelectList(query, "Id", "DisplayText", queueMember.QueueId);
            return View(queueMember);
        }

        // POST: QueueMembers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Priority,TimeInterval,IsAbsent,QueueId,StudentId,Id")] QueueMemberDTO queueMember)
        {
            if (id != queueMember.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _service.UpdateAsync(queueMember);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_service.QueueMemberExists(queueMember.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            var queues = await _queueService.GetAllAsync();

            var query = queues.Select(q => new
            {
                Id = q.Id,
                DisplayText = String.Format("{0} {1} {2} {3}", q.Consultation.Lecturer.SecondName,
                q.Consultation.Subject.Name, q.Consultation.Date, q.IssueCategory.ToString())
            });
            ViewData["QueueId"] = new SelectList(query, "Id", "DisplayText", queueMember.QueueId);

            return View(queueMember);
        }

        // GET: QueueMembers/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id < 0)
            {
                return NotFound();
            }

            var queueMember = await _service.GetByIdAsync(id);
            if (queueMember == null)
            {
                return NotFound();
            }

            return View(queueMember);
        }

        // POST: QueueMembers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _service.DeleteByIdAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

WebMVC/Controllers/SubjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.Entities;
using DAL.Implementation;
using BL.Abstraction;
using BL.DTO.Models;
using Microsoft.AspNetCore.Authorization;

namespace WebMVC.Controllers
{
    public class SubjectsController : Controller
    {
        private readonly ISubjectService _service;

        public SubjectsController(ISubjectService service)
        {
            _service = service;
        }

        // GET: Subjects
        public async Task<IActionResult> Index()
        {
            return View(await _service.GetAllAsync());
        }

        // GET: Subjects/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id < 0)
            {
                return NotFound();
            }

            var subject = await _service.GetByIdAsync(id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        // GET: Subjects/Create
        [Authorize(Roles ="lecturer")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Subjects/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Id")] SubjectDTO subject)
        {
            if (ModelState.IsValid)
            {
                await _service.AddAsync(subject);
                return RedirectToAction(nameof(Index));
            }
            return View(subject);
        }

        // GET: Subjects/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id < 0)
            {
                return NotFound();
            }

            var subject = await _service.GetByIdAsync(id);
            if (subject == null)
            {
                return NotFound();
            }
            return View(subject);
        }

        // POST: Subjects/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Id")] SubjectDTO subject)
        {
            if (id != subject.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _service.UpdateAsync(subject);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_service.SubjectExists(subject.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(subject);
        }

        // GET: Subjects/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id < 0)
            {
                return NotFound();
            }

            var subject = await _service.GetByIdAsync(id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        // POST: Subjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _service.DeleteByIdAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

WebMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@if (User.Identity.IsAuthenticated)
{
    @if (User.IsInRole("lecturer"))
    {
        <div class="text-center my-xl-5">
            <h1>Choose an option to continue working</h1>
        </div>
        <div class="row">
            <div class="col-4">
                <div class="card" style="width: 18rem;">
                    <img src="./img/consult.jpg" height="155" class="card-img-top" alt="No image downloaded">
                    <div class="card-body">
                        <h5 class="card-title">Create consultation</h5>
                        <p class="card-text">To create consultation click below and input required data.</p>
                        <a class="btn btn-primary" style="background-color: rosybrown; border-color: palevioletred" asp-area="" asp-controller="Consultations" asp-action="Create">Create consultation</a>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="card" style="width: 18rem;">
                    <img src="./img/students.jpg" height="155" class="card-img-top" alt="No image downloaded">
                    <div class="card-body">
                        <h5 class="card-title">Get all students</h5>
                        <p class="card-text">To get students click below and choose consultation.</p>
                        <a class="btn btn-primary" style="background-color: rosybrown; border-color: palevioletred" asp-area="" asp-controller="QueueMembers" asp-action="Index">Get students</a>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="card" style="width: 18rem;">
                    <img src="./img/absent1.png" height="155" class="card-img-top" alt="No image downloaded">
                    <div class="card-body">
                        <h5 class="card-title">Mark absent</h5>
                        <p class="card-text">To mark an absent student click below and choose a student.</p>
                        <a class="btn btn-primary" style="background-color: rosybrown; border-color: palevioletred" asp-area="" asp-controller="QueueMembers" asp-action="Index">Mark absent</a>
                    </div>
                </div>
            </div>
            <div class="col-4" style="margin-top: 20px">
                <div class="card" style="width: 18rem;">
                    <img src="./img/subject.jpg" height="155" class="card-img-top" alt="No image downloaded">
                    <div class="card-body">
                        <h5 class="card-title">Create subject</h5>
                        <p class="card-text">To create a subject click below and input data.</p>
                        <a class="btn btn-primary" style="background-color: rosybrown; border-color: palevioletred" asp-area="" asp-controller="Subjects" asp-action="Create">Create subject</a>
                    </div>
                </div>
            </div>
        </div>

    }
    else if (User.IsInRole("student"))
    {
        <div class="text-center my-xl-5">
            <h1>Choose an option to continue working</h1>
        </div>
        <div class="row" style="margin: 0 0 0 15%">
            <div class="col-lg-6">
                <div class="card" style="width: 18rem;">
                    <img src="./img/consult.jpg" height="155" class="card-img-top" alt="No image downloaded">
                    <div class="card-body">
                        <h5 class="card-title">Book for consultation</h5>
                        <p class="card-text">To book for consultation click below and choose consultation.</p>
                        <a class="btn btn-primary" style="background-color: rosybrown; border-color: palevioletred" asp-area="" asp-controller="QueueMembers" asp-action="Create">Book consultation</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="card" style="width: 18rem;">
                    <img src="./img/students.jpg" height="155" class="card-img-top" alt="No image downloaded">
                    <div class="card-body">
                        <h5 class="card-title">Get consultations</h5>
                        <p class="card-text">To get consultation information click below.</p>
                        <a class="btn btn-primary" style="background-color: rosybrown; border-color: palevioletred" asp-area="" asp-controller="Consultations" asp-action="Index">Get consultations</a>
                    </div>
                </div>
            </div>
        </div>
    }
}
else
{
    <h1>Please, login or register to get started</h1>
}